### ISSUE TITLE
How does USBDriver work？

### ISSUE THREAD

**Issue by ZhouYixun** [electricbubble/gwda#12]
I found this code in `NewUSBDriver`
```
if wd.urlPrefix, err = url.Parse("http://" + dev.serialNumber); err != nil {
		return nil, err
}
```

but why `http://xxxxxx` can work in code？

**Comment by electricbubble** [comment]
This `URL` is not used when connecting via `USB`.

This is just to facilitate the log output to locate the device.

https://github.com/electricbubble/gwda/blob/b7fe89cbe6b627cc9ff1862b012a05e55b7c37b1/driver.go#L108-L112

**Comment by ZhouYixun** [comment]
> 

ok ,thx
