### ISSUE TITLE
请问有支持安卓手机的版本吗？

### ISSUE THREAD

**Issue by 914795561** [electricbubble/gwda#3]
请问有支持安卓手机的版本吗？

**Comment by electricbubble** [comment]
已经在做了（进度 `50%` 左右了），可能晚些日子才开放仓库
不过你可以了解下另一个作者的项目 https://github.com/openatx/uiautomator2

**Comment by 914795561** [comment]
请问能出一个实现的教程吗？我最近也在学golang，想找个动手的项目学习一下

**Comment by electricbubble** [comment]
我这个项目的吗？
这里有提供几个简单的例子，可以当作了解
https://github.com/electricbubble/gwda/tree/master/examples

**Comment by electricbubble** [comment]
@914795561 `Android` 版的 [guia2](https://github.com/electricbubble/guia2) 已上传
