### ISSUE TITLE
demo usb连接失败是什么错误

### ISSUE THREAD

**Issue by Xuzan9396** [electricbubble/gwda#4]
![image](https://user-images.githubusercontent.com/24741439/90607831-5aeed600-e234-11ea-9434-981158732538.png)

2020/08/19 15:52:28 连接设备 usb connect: connection refused

**Comment by electricbubble** [comment]
😂 是不是忘记启动 `Xcode` 里的 `wda` 了

**Comment by Xuzan9396** [comment]
@electricbubble  是的， 楼主， 我用夜神模拟器， 有没有支持安卓的包 golang包

**Comment by electricbubble** [comment]
@Xuzan9396 有的哈 [guia2](https://github.com/electricbubble/guia2)
> `server` 端的全部命令都已支持, 个别操作 (比如启动指定的 App) 需要使用 adb 实现，有计划扩展进这个项目里

**Comment by Xuzan9396** [comment]
好的 ， 谢谢楼主， 我会持续关注支持
