### ISSUE TITLE
解析截图失败

### ISSUE THREAD

**Issue by zhanglianxin** [electricbubble/gwda#6]
> 版本：
> * webdriveragent-xcode_12.3.zip `v2.32.2`
> * github.com/electricbubble/gwda `v0.1.1`
> * iOS `13.4.1`

```go
bs, err := driver.Screenshot()
session, _ := driver.ActiveSession()
t.Log(session.SessionId)
if nil != err {
	t.Error("screenshot", err)
} else {
	// dst := base64.StdEncoding.EncodeToString(bs.Bytes())
	// t.Log(dst)
	img, format, err := image.Decode(bs)
	if nil != err {
		t.Error("decode", err) // image: unknown format <===
	} else {
		t.Log(bs.Len(), img, format)
	}
}
```

经浏览器直接请求截图看到，返回的图片 base64 是带有 `\r\n` 换行符的，是否因这个问题解析失败呢？

如下图所示：

![235434.png](https://p.sda1.dev/0/02ed732e3c69eae8b56accc261d26169/235434.png)

**Comment by electricbubble** [comment]
`Golang` 的 `image.Decode(...)` 函数需要提前 `import` 指定的图片格式

```Golang
package main

import (
	"github.com/electricbubble/gwda"
	"image"
	"image/jpeg" // 目标图片格式需要提前 import
	"image/png"  // 目标图片格式需要提前 import
	"log"
	"os"
)

func main() {
	driver, err := gwda.NewUSBDriver(nil)
	if err != nil {
		log.Fatal(err)
	}

	screenshot, err := driver.Screenshot()
	if err != nil {
		log.Fatal(err)
	}
	_ = screenshot

	img, format, err := image.Decode(screenshot)
	if err != nil {
		log.Fatal(err)
	}
	userHomeDir, _ := os.UserHomeDir()
	file, err := os.Create(userHomeDir + "/Desktop/s1." + format)
	if err != nil {
		log.Fatal(err)
	}
	defer func() { _ = file.Close() }()
	switch format {
	case "png":
		err = png.Encode(file, img)
	case "jpeg":
		err = jpeg.Encode(file, img, nil)
	}
	if err != nil {
		log.Fatal(err)
	}
	log.Println(file.Name())
}

```

**Comment by electricbubble** [comment]
`*_test.go` 文件里基本上都有这些函数的常规使用

https://github.com/electricbubble/gwda/blob/master/driver_test.go#L634-L663

**Comment by zhanglianxin** [comment]
> `Golang` 的 `image.Decode(...)` 函数需要提前 `import` 指定的图片格式
> 
> > 如果不需要特定格式的解析, 也可以使用 `_`
> > ```go
> > import (
> >   "image"
> >   _ "image/jpeg"
> >   _ "image/png"
> > )
> > ```
> 
> ```go
> package main
> 
> import (
> 	"github.com/electricbubble/gwda"
> 	"image"
> 	"image/jpeg" // 目标图片格式需要提前 import
> 	"image/png"  // 目标图片格式需要提前 import
> 	"log"
> 	"os"
> )
> 
> func main() {
> 	driver, err := gwda.NewUSBDriver(nil)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	screenshot, err := driver.Screenshot()
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	_ = screenshot
> 
> 	img, format, err := image.Decode(screenshot)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	userHomeDir, _ := os.UserHomeDir()
> 	file, err := os.Create(userHomeDir + "/Desktop/s1." + format)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer func() { _ = file.Close() }()
> 	switch format {
> 	case "png":
> 		err = png.Encode(file, img)
> 	case "jpeg":
> 		err = jpeg.Encode(file, img, nil)
> 	}
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	log.Println(file.Name())
> }
> ```

感谢您的耐心解答，使我学到了 `image` 包的使用方式。
